### ISSUE TITLE
Does it work with micropython V1.12 ?

### ISSUE THREAD

**Issue by pidou46** [tve/mpy-lib#1]
Hi tve,

I'm interested in this pcnt implementation.

Does it work with latest esp32 official firmware ?

Could you give some instruction (in a README) how to build it, or redirect to relevant general doc somewhere please ?

Thanks

**Comment by tve** [comment]
The esp32-counter does not work with v1.12, it needs the native function linking. If you want, you can try it with my firmware: https://github.com/tve/micropython/releases/tag/v1.12-tve2

**Comment by pidou46** [comment]
Thanks for your answer,

I can't test it right now, but maybe later, thanks
