### ISSUE TITLE
sntp timeout

### ISSUE THREAD

**Issue by ubIQio** [tve/mpy-lib#3]
i'm using your sntp client with your excellent mqboard and works fine with your micropython branch esp32-fix-errno-3
 and esp-idf 4.1, but using espidf 4.2 (no bluetooth) with your micropython fork branch esp32-idf42-cmake,  it fails with a timeout eg

I 10939727  sysinfo: {"up":10939,"free":4051008,"mqtt_conn":1}
W 10946697     sntp: pool.ntp.org timed out
W 10958920     sntp: pool.ntp.org timed out

 although the mqtt watchdog feed works fine (i'm not using ssl btw)

does sntp.py need to be changed to work with the modified asyncio / stream.py?

any pointers much appreciated

**Comment by ubIQio** [comment]
turns out this was nothing to do with asyncio, but with changes to RTC.init() which no longer sets times, now using the new time.settime instead and  epoch now being 1970 on POR which meant NTP adjustment was too big .

works fine now, closing

**Comment by tve** [comment]
Sorry for being slow in responding, it looks like you resolved the issue. The time stuff is a bit of a mess, I made https://github.com/micropython/micropython/pull/5973 a while ago, which enables SNTP and then Damien added some other changes in the meantime. I should split that PR so the stuff that is not controversial can get in, but then I already have a pile of PRs pending with no forward progress...

**Comment by ubIQio** [comment]
Yes the whole PR thing is such a shame, it feels like like MPY has such potential but is a victim of its own success.

There are so many forks, its hard to know what to base a product on.  Having been to loboris and back via Pycom and CircuitPython,  your cmake42 fork is about as good as it gets right now for ESP32 IMO.

BTW, trying to add the microhomie convention on top of your MQboard just to have some defined format for topics etc, so tried building for unix as I thought it would be easier. 

Do you use the unix build for development, and if so what is the best way to fake out the network connection?

**Comment by tve** [comment]
So the cmake42 fork is working for you? It doesn't work for me as I described in the PR.
Interesting thought to add the microhomie conventions... can I find those somewhere?
I have not used the unix build for development, only for testing.

**Comment by ubIQio** [comment]
yes working fine, tho' i don't use bluetooth. Have seen no issues on 2 test systems, but only up for a few days...

just using the microhomie repo, from [here](https://github.com/microhomie/microhomie)
It's just to have some defined structure before I add my device nodes.

It sits on a fairly trivial  fork of mqtt.as (with unsubscribe) but your mqtt_async seems very solid so i plan to re work it to use that and run it in MQboard's main  loop.

I'll let you know if the unix route works out for me :)
